const canvas=document.getElementById('heatmap'),ctx=canvas.getContext('2d'),tooltip=document.getElementById('tooltip'),detail=document.getElementById('detail'),lb=document.getElementById('legendBar'),lctx=lb.getContext('2d');
const SERVICES=['api-gateway','auth-service','user-service','payment-svc','notification','scheduler','analytics','cache-layer'];
const HOURS=24,CELL=28,PAD=2;
let data=[];
SERVICES.forEach(svc=>{const row=[];for(let h=0;h<HOURS;h++){const base=Math.random()*100;const errs=Math.floor(Math.random()*(h>8&&h<20?15:3));const warns=Math.floor(Math.random()*20);row.push({total:Math.floor(base+errs+warns),errors:errs,warns,svc,hour:h})}data.push(row)});
function color(v,max){const t=Math.min(v/max,1);if(t<0.25)return`rgba(110,231,183,${0.1+t*2})`;if(t<0.5)return`rgba(96,165,250,${0.3+t})`;if(t<0.75)return`rgba(251,191,36,${0.4+t*0.6})`;return`rgba(248,113,113,${0.5+t*0.5})`}
function draw(){const lw=90;canvas.width=lw+HOURS*(CELL+PAD)+10;canvas.height=SERVICES.length*(CELL+PAD)+30;ctx.fillStyle='#1a1d27';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#555';ctx.font='10px sans-serif';for(let h=0;h<HOURS;h++)ctx.fillText(String(h).padStart(2,'0'),lw+h*(CELL+PAD)+6,12);const max=Math.max(...data.flat().map(d=>d.total),1);data.forEach((row,si)=>{ctx.fillStyle='#6ee7b7';ctx.font='11px sans-serif';ctx.fillText(SERVICES[si],4,22+si*(CELL+PAD)+18);row.forEach((cell,hi)=>{ctx.fillStyle=color(cell.total,max);ctx.beginPath();ctx.roundRect(lw+hi*(CELL+PAD),18+si*(CELL+PAD),CELL,CELL,3);ctx.fill()})})}
canvas.onmousemove=e=>{const r=canvas.getBoundingClientRect();const x=e.clientX-r.left,y=e.clientY-r.top;const lw=90,hi=Math.floor((x-lw)/(CELL+PAD)),si=Math.floor((y-18)/(CELL+PAD));if(hi>=0&&hi<HOURS&&si>=0&&si<SERVICES.length){const c=data[si][hi];tooltip.textContent=`${SERVICES[si]} @ ${String(hi).padStart(2,'0')}:00 — ${c.total} logs, ${c.errors} errors, ${c.warns} warnings`}else tooltip.textContent=''};
canvas.onclick=e=>{const r=canvas.getBoundingClientRect();const x=e.clientX-r.left,y=e.clientY-r.top;const lw=90,hi=Math.floor((x-lw)/(CELL+PAD)),si=Math.floor((y-18)/(CELL+PAD));if(hi>=0&&hi<HOURS&&si>=0&&si<SERVICES.length){const c=data[si][hi];detail.innerHTML=`<strong style="color:#6ee7b7">${c.svc}</strong> at <strong>${String(hi).padStart(2,'0')}:00</strong><br>Total: ${c.total} | <span style="color:#f87171">Errors: ${c.errors}</span> | <span style="color:#fbbf24">Warns: ${c.warns}</span> | Info: ${c.total-c.errors-c.warns}`}};
const grd=lctx.createLinearGradient(0,0,120,0);grd.addColorStop(0,'rgba(110,231,183,0.15)');grd.addColorStop(0.5,'rgba(96,165,250,0.6)');grd.addColorStop(1,'rgba(248,113,113,0.9)');lctx.fillStyle=grd;lctx.fillRect(0,0,120,14);
draw();